[tools]
"aqua:casey/just" = "1.55.1"
"aqua:charmbracelet/glow" = "2.1.2"
"aqua:dandavison/delta" = "0.19.2"
"aqua:Wilfred/difftastic" = "0.69.0"
"aqua:crate-ci/typos" = "1.47.2"
"aqua:ducaale/xh" = "0.26.1"
"aqua:getsops/sops" = "3.13.2"
"aqua:gitleaks/gitleaks" = "8.30.1"
"aqua:google/go-containerregistry" = "0.21.7"
"aqua:hadolint/hadolint" = "2.14.0"
"aqua:hatoo/oha" = "1.14.0"
"aqua:jesseduffield/lazydocker" = "0.25.2"
"aqua:jesseduffield/lazygit" = "0.62.2"
"aqua:koalaman/shellcheck" = "0.11.0"
"aqua:mikefarah/yq" = "4.53.3"
"aqua:mvdan/sh" = "3.13.1"
"aqua:opentofu/opentofu" = "1.11.11"
"aqua:oras-project/oras" = "1.3.2"
"aqua:rhysd/actionlint" = "1.7.12"
"aqua:sharkdp/hyperfine" = "1.20.0"
"aqua:tamasfe/taplo" = "0.10.0"
"aqua:wagoodman/dive" = "0.13.1"
"aqua:watchexec/watchexec" = "2.5.1"
"aqua:fullstorydev/grpcurl" = "1.9.3"
"aqua:anchore/syft" = "1.46.0"
"aqua:aquasecurity/trivy" = "0.72.0"
"aqua:bootandy/dust" = "1.2.4"
"aqua:Byron/dua-cli" = "2.37.1"
"aqua:dprint/dprint" = "0.55.1"

[settings]
experimental = true
