#!/bin/bash
#MISE description="Post-install setup"
#MISE depends=["setup-starship", "setup-direnv", "setup-atuin", "expose-tools", "setup-blesh", "setup-zoxide"]

echo "Post-install configuration complete."
