#!/bin/bash
#MISE description="Setup Zoxide"
set -euo pipefail

bashrc="/etc/bash.bashrc"
line='eval "$(/usr/local/bin/zoxide init bash)"'

tmp_file="$(mktemp)"
awk -v line="$line" '$0 != line { print }' "$bashrc" >"$tmp_file"
mv "$tmp_file" "$bashrc"

printf '%s\n' "$line" >> "$bashrc"
